[package]
name = "rust-async-request"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.0", features = ["blocking"]}
error-chain = "0.12.4"
tokio = { version = "1.39.3", features = ["full"] }
