[package]
name = "rust-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { Version = "0.8.1", features = [ "runtime-async-std-native-tls", "sqlite"] }
async-std = { Version = "1.12.0", features = ["attributes"] }
futures = "0.3.30"

