[package]
name = "rust-extract-links"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = "0.12.7"
select = "0.6.0"
tokio = { version = "1.40.0", features = ["full"] }
