[package]
name = "Rust-CALL-API"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.127"
serde = {version = "1.0.209", featurees = ["derieve"] }
reqwest = { version = "0.12.7", features = ["json"] }
tokio = { version = "1.39.3", features = ["full"] }